version: "3.7"
services:
  app:
    build:
      args:
        user: dev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: lara
    container_name: lara-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./.docker/app/php-fpm.ini:/usr/local/etc/php/conf.d/99-app.ini
    networks:
      - lara

  nginx:
    image: nginx:alpine
    container_name: lara-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - lara

networks:
  lara:
    driver: bridge